opengeospatial/ogc-geosparql

1.1/geo.ttl

Remove unnecessary/unwanted spaces and newlines in annotation text (see [issue 50](https://github.com/opengeospatial/ogc-geosparql/issues/50)).

Update geo.ttl: remove spaces and newlines

---

1.1/geo.ttl
1.1/spec/11-Part-08.adoc
1.1/spec/13-Part-10.adoc

I have extended the Geometry Extension section of the GeoSPARQL specification to include a definition for a GeoJSON literal.
The ontology has also been extended by a geo:asGeoJSON property and a geo:geoJSONLiteral.
I had the following considerations:
- I chose to represent GeoJSON using a GeoJSON literal and not using the rdf:json relation because other serializations of geometries in JSON exist, for example ESRIJSON, TopoJSON, or even pure JSON files with lat/lon geocoordinates attached. Whether or not to leave it this way is a matter of discussion
- GeoJSON literals do not allow the definition of a CRS in the literal as opposed to WKT and GML as the GeoJSON standard only allows one CRS (WGS84) to be used
- GeoJSON literals are defined by the Geometry Object of the GeoJSON specification, …

GeoJSON literals for GeoSPARQL

---

1.1/geo.ttl
1.1/spec/11-Part-08.adoc

This definition if approved closes issue #69 
KML like GeoJSON requires a WGS84 coordinate reference system for every geometry to be defined.
KML, as opposed to other literals, does not define an empty geometry.
It requires at least one coordinate to be present in the coordinate tag of every geometry according to the KML specification. 
However, we may define an empty KML geometry as the empty literal (as proposed in my draft of the specification). 
Apart from that, I see no issues in including KML literals into GeoSPARQL.

KML Literal definition

---

.github/workflows/pylode.yml
1.0/profile.ttl
1.0/sf_geometries.ttl
1.1/sf_geometries.ttl
index.html

I created a CI process with Github Actions which builds a Github page in a separate branch of this repository.
The Github page contains ontology documentation generated by pylode for GeoSPARQL 1.0 and GeoSPARQL 1.1 from the currently available geo.ttl files.
The result looks like this: https://situx.github.io/ogc-geosparql/
While the style can definitely be improved I think it is important to verify the TTL files we post I the repository automatically using CI.
I fixed a missing namespace during this process.
However, I did not manage to create an ontology documentation for all of the ttl files as they require an ontology definition inside. Maybe Nic can help with that?
Would be nice to be able to show the current improvements of the GeoSPARQL ontology on a Github page to anyone who is …

Continuous Integration process

---

1.1/geo.ttl
1.1/spec/11-Part-08.adoc
1.1/spec/18-Bibliography.adoc

This is an updated re-issuing of PR #52.
I have not defined the literal content other than the DGGS identifier (an IRI) as the content should be left to DGGS specs.
I have included an example of a simple DGGS literal for AusPIX.
Closes #2

DGGS WKT literval v2

---

1.1/funcsrules.ttl
1.1/geo.ttl
1.1/spec/17-Annex-B.adoc

This PR adds ID attributes to examples in the documentation. These ID's can be used in the ontology to form skos:example links.

Add example anchors and links

---

1.1/geo.ttl

Add property :hasDefaultGeometry to geo.ttl in version 1.1.  It is still absent in version 1.0 (assuming it won't be published again).
Fixes #123

Add property :hasDefaultGeometry to geo.ttl

---

README.md

It appears there is a need for people to already cite the working documents we produce in the continuous integration process, as shown by issue #130 
I think we should give people guidance and define how we want to be cited, by providing a BibTeX definition.
As I am not sure how to best define it I copied a common one from Google Scholar and updated it.
We can modify it until we are satisfied and add it to the Readme.

Citation of the working document

---

1.1/geo.ttl

Define` hasDefaultGeometry` and `defaultGeometry` as duplicates.
Fixes [issue 128](https://github.com/opengeospatial/ogc-geosparql/issues/128) and [issue 30](https://github.com/opengeospatial/ogc-geosparql/issues/30).

Update geo.ttl: resolve conflict between defaultGeometry and hasDefaultGeometry

---

1.1/funcsrules.ttl
1.1/geo.ttl
1.1/profile.ttl
1.1/sa_functions.ttl
1.1/sf_geometries.ttl

Added @base statement to provide baseuri. Without trailing hash to align with the ontology definition statement. Closes #147

Update geo.ttl to add a base uri statement

---

1.1/profile.html
1.1/profile.ttl
1.1/validation.ttl

This is a trivial PR that just fixes links in the profile declaration to the SHACL validator still being worked on.
I'm merging this without review since it's trivial.

Minor: change profile references to validator

---

1.1/examples/demo-dataset.ttl
1.1/spec/09-Part-06.adoc
1.1/spec/11-Part-08.adoc

This PR addresses the comment https://github.com/opengeospatial/ogc-geosparql/pull/173#issuecomment-896896673 by re-implementing the information of the extended example's `dcterms:isPartOf` property to the inverse `rdfs:member` to align with our ontology definitions of collections.

dcterms:isPartOf flipped to rdfs:member

---

1.1/spec/01-Preamble.adoc
1.1/spec/08-Part-05.adoc
1.1/spec/11-Part-08.adoc
1.1/spec/17-Annex-B.adoc

As discussed two meeting back, here AusPIX DGGS is removed from normative standing but retained as an example for DGGSes.

AusPIX removed from normative standing

---

1.1/geo.ttl
1.1/spec/09-Part-06.adoc
1.1/spec/17-Annex-B.adoc

This PR was motivated by the Issue raised in the last meeting about the domain of Spatial Measure properties.
Closes Issue #178

SpatialMeasure props to use SpatialObject not Feature for domain

---

1.0/citeme.bib
1.1/spec/citeme.bib

This pull request includes bibtex files which I would like to include
* In the repository
* Render on the Github page
I find it very important that we communicate how to cite the standard properly.
If you look at Google Scholar for GeoSPARQL standard, you will see that there is a variety of options to choose from, not all of them great. So we should communicate how we want to be cited.
I would encourage everyone to edit these bibtex files until we all agree.

Bibtex citation

---

1.1/geo.ttl
1.1/spec/09-Part-06.adoc

This PR adds two properties: `hasMetricPerimeter` and `hasPerimeter`. It also relaxes the restrictions on the length and area properties described in the spec. Resolves [issue 204](https://github.com/opengeospatial/ogc-geosparql/issues/204).

Add perimeter properties

---

1.1/reqs.ttl
1.1/validator.ttl

Elements in reqs.ttl are now associated with the <http://www.opengis.net/def/spec-element/> namespace as defined by OGC.

Updated requirements to make use of the ogc spec element namespaces

---

1.1/validator.ttl

Removes shapes S2, S21, and S32-geometryClass-hasGeometry-sub so that standalone Geometries and Features do not generate violations. Also corrects examples in S32-geometryClass-hasSerialization-sub.

remove SHACL rules that forbid standalone Geometries and Features

---

1.1/funcsrules.ttl
1.1/geo.ttl
1.1/profile.html
1.1/profile.ttl
1.1/reqs.ttl
1.1/sa_functions.ttl
1.1/sf_geometries.ttl
1.1/validator.ttl

Closes #60
Although we haven't attained a full RDF license, we have a stable reference in all assets for now. We will replace this with an RDF reference IF the OGC presents one before 1.1 is released, if not, the RDF version can be referenced in future GeoSPARQL work.

license & rights added to all assets

---

1.1/validator.ttl

For our GeoSPARQL benchmark I have tried to validate the benchmark dataset we use with the SHACL shapes.
You can find the dataset here: https://github.com/OpenLinkSoftware/GeoSPARQLBenchmark/blob/master/src/main/resources/gsb_dataset/dataset.rdf
I have changed the following things in the shapes:
- For all literal types: Check also for empty literals and consider whitespace at the beginning and end of regexes. Using pyshacl this does not seem to work for multiline literals though 
I have observed the following behaviors when applying the shapes:
- The benchmark dataset contains the self-defined relations my:hasExactGeometry and my:hasPointGeometry which are rdf:subPropertyOf geo:hasGeometry which cause a validation error when applying the SHACL shapes, but should not
- Shape …

Fixes for SHACL shapes

---

1.1/spec/11-Part-08.adoc

Add a recommendation to use QUDT for arbitrary units, and refer to that recommendation where appropriate. Resolves [issue 259](https://github.com/opengeospatial/ogc-geosparql/issues/259).

recommend QUDT as UOM vocabulary

---

1.1/spec/11-Part-08.adoc

Add an explanation of the unit argument of geof:distance. Fixes [issue 273](https://github.com/opengeospatial/ogc-geosparql/issues/273).

definition of geof:distance

---

1.1/geo.ttl

Declare equivalence of topological relationships in different families. Resolves [issue 267](https://github.com/opengeospatial/ogc-geosparql/issues/267).

declare equivalence of topological properties

---

1.1/sf_geometries.ttl
1.1/spec/00-GeoSPARQL.html
1.1/spec/13-Part-10.adoc
1.1/spec/18-Annex-C.adoc

Just some simple improvements to SF Vocab documentation and examples.
The important bits for review: 
* Class Hierarchy given: https://raw.githack.com/opengeospatial/ogc-geosparql/0f3930184436797ed2bc38dadba213fea45f5a55/1.1/spec/00-GeoSPARQL.html#_geometry_class_hierarchy
* Annex C examples: https://raw.githack.com/opengeospatial/ogc-geosparql/0f3930184436797ed2bc38dadba213fea45f5a55/1.1/spec/00-GeoSPARQL.html#_c_1_1_7_simple_features_classes
Closes #247

e.g. for SF Geometry classes

---

1.1/spec/11-Part-08.adoc

The introduction of section 8 was about too many different subjects, to my taste. I feel inserting a heading and thereby creating  a subsection improves the text. Fixes [issue 295](https://github.com/opengeospatial/ogc-geosparql/issues/295).

section 8: new subsection split off intro

---

1.1/spec/11-Part-08.adoc

Changes a wrong namespace in the GML example as discovered by #330 
Closes #330

Changed wrong GML namespace in GML example

---

1.1/geo.ttl
1.1/spec/02-Introduction.adoc
1.1/spec/11-Part-08.adoc
1.1/spec/22-Bibliography.adoc

I have:
* updated the 19107 reference to the latest
* reduced the references to 19107 to just one: a non-normative, comparative, reference for Geometry class
* updated references to GML from 3.2.1 to 3.2.2 to capture ISO alignment and remove a direct 19107 reference
Closes #357

updated and reduced references to 19107; updated GML reference

---

1.1/geo.ttl

Replaced character U+2013 (en dash) with U+002d (hyphen) to avoid ttl parse problem. A user of I think topquadrant brought this to my attention.

replace en dash with hyphen

---

1.0/funcsrules.ttl
1.0/geo.ttl
1.0/profile.ttl
1.0/servicedescription_allfunctions.ttl
1.0/servicedescription_conformanceclasses.ttl
1.0/servicedescription_extensions.ttl
1.0/sf_geometries.ttl
1.1/funcsrules.ttl
1.1/geo.ttl
1.1/profile.ttl
1.1/reqs.ttl
1.1/sa_functions.ttl
1.1/servicedescription/servicedescription_all_functions.ttl
1.1/servicedescription/servicedescription_conformanceclasses.ttl
1.1/servicedescription/servicedescription_extensions.ttl
1.1/sf_geometries.ttl

This PR does two things:
1. Ensures all RDF files have `versionInfo` and `versionIRI` properties
2. Applying consisted formatting to the Turtle in all RDF files - "LongTurtle", as per RDFlib's serializer (see http://rdftools.kurrawong.net/convert)
This is an editorial PR - no content changes!
Closes #373

RDF versions

---

1.1/funcsrules.ttl
1.1/spec/11-Part-08.adoc

Updates the definition of geof:area. Fixes [issue 381](https://github.com/opengeospatial/ogc-geosparql/issues/381).

Area function definition

---

1.1/funcsrules.ttl
1.1/spec/11-Part-08.adoc
1.1/spec/17-Annex-B.adoc

Ensures we have 
* paired functions with properties
* e.g. `geof:perimeter` for `geo:hasPerimeter`
* metric/non-metric pairs 
* e.g. `geof:perimeter` & `geof:metricPerimeter`
* return types matching function
* e.g. `geof:perimeter`  returns an `rdf:Resource` where as `geof:metricPerimeter` returns an `xsd:double`
Also adds all SFA functions to Table _B.2 GeoSPARQL to SFA Functions Mapping_. We were missing lots.
In your reviews, please indicate what we should do about the un-supported SFA functions.

Fix Non-Top functions listing and SFA comparison

---

1.1/funcsrules.ttl
1.1/spec/11-Part-08.adoc

Closes #401
I also added corrections to the function definitions, so that each function now has a clickable function URI.
One question:
I added the phrase, "If no unit parameter is given, the result is returned in the unit of the spatial reference system"
Should we add that to all other non-metric functions as well, or should I remove it?
We have not talked about optional parameters yet, but it seemed logical to me to add it and comparable implementations like PostGIS also work this way.

Add perimeter to spec

---

1.1/sf_geometries.ttl

Responds to #270 but doesn't fix the underlying issue.

Fixing typo in Simple Features spec in our corresponding vocab

---

1.1/spec/11-Part-08.adoc

Closes #447
I think @wouterbeek is correct so adopting his suggestions.
Also, I think it's wrong to expect UoM to be specified as an `xsd:anyURI` literal given UoM specification is usually like this
```
:some-length [
qudt:value "350" ;
qudt: unit <https://qudt.org/vocab/unit/KiloM> ;  # kilometres
] ;
```
where an IRI, not a URL literal, is used, so I have changes all units to `rdfs:Resource` too.

Addressing Issue 447

---

spec/11-Part-08.adoc

Issue #477 suggested to clarify that the minimum and maximum XYZ coordinate functions return the coordinate in the SRS of the geometry which was given as a parameter
Closes #477

Clarifications for minXYZ functions

---

spec/ontology/vocabularies/geo.ttl

The skos:example links in geo.ttl wrongly point to annex B and not annex C as pointed out by #473
Closes #473

Fix wrong example links pointing to annex B instead of annex C

---

alignments/schemaorg-alignments.ttl

One instance of "Geometry" was spelled "Geomery"
(See also: https://schema.org/GeospatialGeometry )

Fix typo in schemaorg-alignments.ttl

---

spec/sections/10-topology_extension.adoc
vocabularies/geo.ttl

Closes #510
Adds topological relations missing from geo.ttl and updates the specification with better links in the topological relation equivalences table.
@VladimirAlexiev

More topological relation equivalences

---

spec/sections/11-geometry_extension.adoc
vocabularies/functions.ttl

Closes #503
This pull request attempts to define a default parameter in the transform function.
My main question here is:
Is that the way you define a default parameter in the spec?
Or is the correct way to do that to define two function definitions?
If we define default parameters like this in the future, is that understandable enough for implementers?
Also; A good idea to revisit #110 in this discussion

Default parameter for transform function

---

vocabularies/geocoding.ttl

Closes #444 
This pull request collects URIs and classes for Geocoding Systems which should be registered at the OGC Naming Authority.
The URIs defined in this vocabulary should eventually after review by OGC be used in GeoCode Literals.

Geocoding Vocabulary

---

spec/sections/11-geometry_extension.adoc
spec/sections/ab-functions_summary.adoc
vocabularies/functions.ttl

https://github.com/opengeospatial/ogc-geosparql/issues/556

556 geometry extrusion
