opengeospatial/ogc-geosparql

- 1.1/geo.ttl
This PR contains removal of duplicate properties (that can be created with inference, if needed), modernisation of DCTERMS removal of attribution per-element and modern, W3C-style, attribution at the whole-of-ontology level.
I have only included me and @jabhay in the contributors field now to show off the style of contributor indication used (schema.org) and to ask for your initial reviews of this and your attribution details before completing this PR.
@jabhay can you please supply OGC direction on attribution?
> Tidy annotations & attribution

- 1.0/profile.ttl
- 1.0/rules.rifps
- 1.1/funcsrules.ttl
- 1.1/spec/11-Part-08.adoc
Improves the Functions & Rules vocabulary in line with points raised in Issue #51.
I have not addressed the issue of repeated `prefLabel` values as now the things with repeated values are listed in separate Collections (and also all-term Collections) so they should be easier to differentiate.
Closes #51
> 1.1 improve funcrules

- 1.1/geo.ttl
> updated SpatialMeasure defn

- README.md
> small README updates

- 1.1/funcsrules.ttl
- 1.1/spec/11-Part-08.adoc
I added more functions that we defined properties for, but which did not have a function representation.
Some functions involve returning a metric value which I normalized to meters in the function specification.
This is probably something to discuss.
> Added more functions to conform with Simple Features SQL

- 1.1/spec/17-Annex-B.adoc
> Issue 29: fix examples in Appendix B

- 1.1/spec/02-Introduction.adoc
- 1.1/spec/06-Part-03.adoc
- 1.1/spec/07-Part-04.adoc
- 1.1/spec/spec-td.html
@FransKnibbe I've added a few basic definitions for Semantic Web things and have left the "Spatial" section empty for you to add to!
I've also added a couple of missing Normative References, RDF for instance.
Rendered version of Spec with Ts & Ds: https://raw.githack.com/opengeospatial/ogc-geosparql/simple-td/1.1/spec/spec-td.html
> Simple Terms & Defs

- 1.1/sa_functions.ttl
- 1.1/spec/11-Part-08.adoc
As discussed in the last call, prefixes have now been added to the aggregate functions
> Added prefixes to aggregate functions

- 1.1/geo.ttl
- 1.1/spec/09-Part-06.adoc
- 1.1/spec/11-Part-08.adoc
> standardizing captalization of Feature & Geometry

- 1.1/reqs.ttl
- 1.1/spec/09-Part-06.adoc
- 1.1/spec/16-Annex-A.adoc
Fixing IRI of Spatial Object Properties Req and the Req listing in Annex & RDF
Fixes #211
> fix issue 211

- 1.1/spec/00-GeoSPARQL.adoc
Editors ordered as per email discussion. Paul only made one commit so far, to add a BASE URI to the ontology!
> ordered editors as per email discussion

- 1.1/spec/21-Bibliography.adoc
* add in links from Issue #199 
* sort Refs by Author, Date
* improve a couple of refs' formatting
> Refs update

- 1.1/alignments/bfo.alignments.ttl
- 1.1/spec/20-Annex-E.adoc
Added:
* Basic Formal Ontology
> More allignments

- 1.1/geo.ttl
Bring collection definitions inline with conventions; no need to repeat type or label in the definition.
> Update definitions of collections

- 1.1/translations/geo_de.ttl
> Fixed translations to conform to the more general definition of Feature

- 1.1/spec/00-GeoSPARQL.html
- 1.1/spec/18-Annex-C.adoc
Small PR
See the relevant, very slightly updated, section: https://raw.githack.com/opengeospatial/ogc-geosparql/ca0e865a909a22b81b58cb057e80c68387f6d099/1.1/spec/00-GeoSPARQL.html#_c_2_4_example_geometry_serialization_conversion_functions
Fixes #182
> Fixes #182

- 1.1/spec/00-GeoSPARQL.adoc
> fixes #306

- 1.1/alignments/locn-alignments.ttl
- 1.1/spec/20-Annex-E.adoc
Summary of proposed revisions:
- Make `geo:Geometry` a subclass of `locn:Geometry`
- Editorial changes
> Proposed revision to GeoSPARQL to LOCN mapping

- 1.1/funcsrules.ttl
- 1.1/spec/11-Part-08.adoc
Fixes [issue 286](https://github.com/opengeospatial/ogc-geosparql/issues/286).
> Add functions for metric buffer and metric distance

- 1.1/spec/10-Part-07.adoc
- 1.1/spec/17-Annex-B.adoc
> harmonise Annex w Ch 7 tables

- 1.1/release_notes/sections/annex-history.adoc
- 1.1/release_notes/sections/clause-0-preface.adoc
- 1.1/release_notes/sections/clause-1-intro.adoc
- 1.1/release_notes/sections/clause-2-references.adoc
- 1.1/release_notes/sections/clause-3-terms.adoc
- 1.1/release_notes/sections/clause-6-substantive.adoc
- 1.1/release_notes/sections/clause-7-future.adoc
Link fix & formatting updates to Release Notes + Abstract, Future Work & History.
If this is merged, I'll approve the original Release Notes PR
> Release Notes Update

- 1.1/release_notes/releasenotes.adoc
- 1.1/release_notes/sections/annex-bibliography.adoc
- 1.1/release_notes/sections/clause-1-intro.adoc
- 1.1/release_notes/sections/clause-3-terms.adoc
- 1.1/release_notes/sections/clause-6-substantive.adoc
Adds the note requested by @FransKnibbe in Issue #170.
Also makes a number of simple updates to the Release Notes. Itemised in commits.
Closes Issue #170
> Fix Issue 170

- 1.1/spec/01-Preamble.adoc
- 1.1/spec/02-Introduction.adoc
- 1.1/spec/05-Part-02.adoc
- 1.1/spec/08-Part-05.adoc
- 1.1/spec/09-Part-06.adoc
- 1.1/spec/11-Part-08.adoc
Some minor edits from a full pass over the main spec document.
> some editorial changes

- 1.1/alignments/as-alignments.ttl
- 1.1/spec/20-Annex-E.adoc
I came across the Activity Streams Vocabulary recently https://www.w3.org/TR/activitystreams-vocabulary/ and created alignments for this vocabulary
> Alignments for W3C Activity Streams Vocabulary

- 1.1/spec/11-Part-08.adoc
- 1.1/spec/17-Annex-B.adoc
Fixed the specification of geometry N to be actually useful
> Bugfix: Geometry N function did not have a parameter for N

- 1.0/funcsrules.ttl
- 1.1/funcsrules.ttl
I added function parameter and return value definitions to the funcsrules vocabulary, only for functions.
I used the FNO vocabulary: https://fno.io/spec/#dfn-function-declaration
> Added function parameter definitions to funcsrules

- 1.1/spec/11-Part-08.adoc
- 1.1/spec/22-Annex-G.adoc
As discussed, hanging TTL removal in 8.6
> Removed hanging turtle in 8.6 and added history for full review

- 1.1/spec/09-Part-06.adoc
- 1.1/spec/16-Annex-A.adoc
> Small editorial fixes

- 1.1/spec/11-Part-08.adoc
> Add centroid definition to GeoSPARQL 1.1 spec

- 1.1/spec/19-Annex-D.adoc
> Fix broken links in GeoSPARQL 1.1 Annex

- 1.1/spec/16-Annex-A.adoc
> Fix bad wording in GeoJSON Abstract Test Suite

- 1.1/spec/01-Preamble.adoc
- 1.1/spec/05-Part-02.adoc
- 1.1/spec/08-Part-05.adoc
- 1.1/spec/16-Annex-A.adoc
- 1.1/spec/17-Annex-B.adoc
- 1.1/spec/18-Annex-C.adoc
- 1.1/spec/19-Annex-D.adoc
- 1.1/spec/20-Annex-E.adoc
- 1.1/spec/21-Annex-F.adoc
- 1.1/spec/22-Annex-G.adoc
- 1.1/spec/23-Bibliography.adoc
> fix the duplicated Annex menu wording

- spec/11-Part-08.adoc
- spec/19-Annex-D.adoc
> Correcting link labels of Annex D

- vocabularies/functions.ttl
- vocabularies/rules.ttl
> Change funcs and rules namespaces to geof and geor (GeoSPARQL 1.0 Branch)

- vocabularies/rules.ttl
> Change funcs and rules namespaces to geof and geor (GeoSPARQL 1.1 Branch)

- geosparql10/profile.adoc
- geosparql10/profile.html
- geosparql10/profile.py
- geosparql11/profile.adoc
- geosparql11/profile.html
- geosparql11/profile.py
- geosparql11/releasenotes.html
* generate profile HTML from TTL via ADOC
> fix missing profile.html

- vocabularies/geo.ttl
Closes #509 
Closes #474
Issues to clarify:
> Change empty namespace in geo.ttl to geo:

- servicedescription/servicedescription_all_functions.ttl
- servicedescription/servicedescription_conformance_classes.ttl
- servicedescription/servicedescription_core.ttl
- servicedescription/servicedescription_extensions.ttl
Closes #544 
This pull request reworks service descriptions to make them more modular as suggested by @VladimirAlexiev
> Increased modularity of service descriptions

- vocabularies/functions.ttl
https://github.com/opengeospatial/ogc-geosparql/issues/626
> Corrected prefix for geof:numInteriorRing

- vocabularies/functions.ttl
https://github.com/opengeospatial/ogc-geosparql/issues/623
> Corrected prefix for geof:metricDistance

- vocabularies/functions.ttl
https://github.com/opengeospatial/ogc-geosparql/issues/622
> Corrected prefLabel for geof:dimension
